### ISSUE TITLE
Geen windows potato support

### ISSUE THREAD

**Issue by Marcwasmasjien** [DimitriTheFox/FileCrypter#4]
I wanted to run this program on my windows potato 96, but it doesn't run. can you make it portable?
[Niet mij klikken.zip](https://github.com/DimitriTheFox/FileCrypter/files/519421/Niet.mij.klikken.zip)

**Comment by DimitriTheFox** [comment]
Still working on a download fix. Please keep looking in the builds folder. As for now, that programs installer doesn't work.

**Comment by DimitriTheFox** [comment]
Portable download created, program should work now.
